# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: DownloadSecureFile@1 
    inputs:
      secureFile: 'parameters.json'
    displayName: 'archivo parameters.json'
  
  - script: jq --version
    displayName: 'jq instalado'


  - task: CopyFiles@2
    displayName: 'Copy Files to: $(System.DefaultWorkingDirectory)'
    inputs:
      SourceFolder: '$(Agent.TempDirectory)'
      Contents: 'parameters.json'
      TargetFolder: '$(System.DefaultWorkingDirectory)'

  - task: CmdLine@2
    displayName: 'dando nombre al archivo del enviroment de $(PROJECT_ID)'
    inputs:
      script: |
        mv $(System.DefaultWorkingDirectory)/parameters.json $(System.DefaultWorkingDirectory)/.env 

  - script: |
      ls -la
      cat .env
    displayName: 'Listar archivos'
  
  - script: 
     nombre = $(echo cat .env | jq -r Nombre[0].name)
     profesion = $(echo cat .env | jq -r 'Profesion[0].primero')
     universidad = $(echo cat .env | jq -r 'Profesion[1].universidad2.')
     precio = $(echo cat .env | jq -r 'Profesion[1].precio[2]')
     
     echo "$nombre es $profesion de la $universidad y gana $precio"

    displayName: 'Primera tarea'
     


